---
spring:
  rabbitmq:
    host: "${RABBITMQ_HOST}"
  data:
    mongodb:
      host: "${MONGODB_HOST}"
existing:
  endpoint:
    pcfHosts: "${EXISTING_HOSTS}"
    name: cassandra
    port: 9092
#haproxy:
#  uri: "https://${SERVICE_KEY_MANAGER}/agents/${HAPROXY_AGENT_ID}/schemas?type=listen"
